version: '3.9'

networks:
  app-tier:

services:
  web:
    networks:
      - app-tier
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db-postgres
    environment:
      - 'DJANGO_DEBUG=True'
      - 'POSTGRES_URI=psql://postgres-user:postgres-password@db-postgres:5432/postgres-database'
      - 'REDIS_URI=redis://redis-cache:6379/1'
    
  db-postgres:
    networks:
      - app-tier
    image: postgres:15.5
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: postgres-database
      POSTGRES_USER: postgres-user

  redis-cache: 
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    
  minio:
    networks:
      - app-tier
    image: bitnami/minio:2024.3.15
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: minio-root-user
      MINIO_ROOT_PASSWORD: minio-root-password


volumes:
  postgres_data:
  minio_data: